### ISSUE TITLE
Sometime the dashboard can't be loaded

### ISSUE THREAD

**Issue by GZ315200** [edp963/davinci#981]
- version
Davinci 3.0

- issue
![xPgGJu2Q4YwAqLrN__thumbnail](https://user-images.githubusercontent.com/11797588/58925515-5eef1f00-877a-11e9-9cf7-a41bde83f2f5.jpg)

- descirption
Sometime the dashboard can't be loaded

**Comment by AndyFong** [comment]
We have met this problem in our environment.  

We found it is caused by multiple simultaneous ajax requests by charts in dashboard, and they are all slow-queries. Due to the browser simultaneous request number limits by 6 for each domain, so only the slow-queries responses return and make the browser request source idle,  after that the request of fetching dashboard portal tree data is sent really.

Please make sure that in your environment, does the ~Loading tree~ problem occur after switch dashboard portal with slow-query chart in it? And if not, please tell us the reproduction steps.

**Comment by gygesM** [comment]
@AndyFong  Hi, Andy. As you said, this is  a  _Loading_ tree problem . So  what should I do to fix it? Please give me a help. Thanx

**Comment by AndyFong** [comment]
We will refactor ajax request module with a todo feature that cancel all the pending ajax requests related to previous dashboard when switch dashboard portal to release the chrome source. But currently it is still a problem when comes to slow-query charts in dashboard.

**Comment by gygesM** [comment]
@AndyFong  Good job. Hope you guys fix it by soon.
